### ISSUE TITLE
Verify Performance of the Segmenter

### ISSUE THREAD

**Issue by davidkroodsma** [SkyTruth/gpsdio-segment#33]
I’ve been looking into why some vessels are acting weird on their segments.

This investigation was spurred on because Juan at UCSB has been calculating total hours on the sea to calculate cost.

In the time normalization I use, each point is assigned half the number of hours to the previous point, plus half the number of hours to the next point. If the point is at the beginning or end of a segment, then I add 12 hours, because we are using 24 hours as the minimum gap until we start a new segment.

We could make it smaller than 12 hours, ​_but_​ if everything is working right, then it should give the right amount of time ( because a gap of 24 hours creates a new segment, so adding 12 hours to that point time normalizes everything). And for most vessels, if you sum up all the hours of all the points, and then count the number of calendar days, you find that each vessel has close to 24 hours per day once you do some noise filtering. (edited)

A few vessels, which aren’t spoofing, have >100 hours per day.

Vessel 987357559 has a relatively normal looking track in 2015:

![987357559](https://cloud.githubusercontent.com/assets/3111114/17268094/5db83bca-55d3-11e6-9b12-0d70f01bf67d.png)

vessel 987357559 in 2015, with alternating segments colored differently.

![987357559_segs](https://cloud.githubusercontent.com/assets/3111114/17268096/6a81e072-55d3-11e6-8b3f-42ee4e9bffa8.png)

So, what’s happening with this vessel? Here’s a query that looks at what happens when two consecutive points have different segments, and the distance and time and implied speed between the two (and using the noise reduction that I use in general):

```
SELECT
  round((timestamp - last_timestamp)/(1000000*60*60),2) hours_diff,
  integer((ACOS(COS(RADIANS(90-lat)) *COS(RADIANS(90-last_lat)) +SIN(RADIANS(90-lat)) *SIN(RADIANS(90-last_lat)) * COS(RADIANS(lon-last_lon)))*6371000)) last_gapmeters,
  round( (ACOS(COS(RADIANS(90-lat)) *COS(RADIANS(90-last_lat)) +SIN(RADIANS(90-lat)) *SIN(RADIANS(90-last_lat)) * COS(RADIANS(lon-last_lon)))*6371) / ((timestamp - last_timestamp)/(1000000*60*60)) , 2)
  implied_speed_km_per_hour,
  *
FROM (
  SELECT
    lat,
    lon,
    timestamp,
    LAG(timestamp,1) OVER (PARTITION BY mmsi ORDER BY timestamp) last_timestamp,
    LAG(lat,1) OVER (PARTITION BY mmsi ORDER BY timestamp) last_lat,
    LAG(lon,1) OVER (PARTITION BY mmsi ORDER BY timestamp) last_lon,
    LAG(seg_id,1) OVER (PARTITION BY mmsi ORDER BY timestamp) last_seg_id,
    seg_id,
    speed
  FROM (
    SELECT
      hours,
      mmsi,
      lat,
      lon,
      timestamp,
      seg_id,
      speed
    FROM
      TABLE_DATE_RANGE([pipeline_classify_logistic_715_fishing.], TIMESTAMP("2015-01-01"), TIMESTAMP("2015-12-31"))
    WHERE
      mmsi = 987357559
      AND lat < 90
      AND lat > -90
      AND lon > -180
      AND lon < 180)
  WHERE
    seg_id NOT IN (
    SELECT
      seg_id
    FROM
      [scratch_david_seg_analysis_715.2015_segments]
    WHERE
      (point_count<20
        AND terrestrial_positions = point_count)
      OR ((min_lon >= 0 // these are almost definitely noise
          AND max_lon <= 0.109225)
        OR (min_lat >= 0
          AND max_lat <= 0.109225) ))
  ORDER BY
    timestamp)     
    where last_seg_id != seg_id
```

[987357559.xlsx](https://github.com/SkyTruth/gpsdio-segment/files/391716/987357559.xlsx)

You see that the implied speed is often above the threshold — and also that the actual speed on this mmsi device appears to be screwed up (always registering very high values) — but there are also some relatively slow implied speeds with small time gaps that should be in the same segments?

There are a number of boats like this, and it throws of the time normalization for them. Is the segmenter doing what it is supposed to? And what do do we do with these weird boats?

**Comment by pwoods25443** [comment]
closing in favor of #41
